name: 🌙 Update README Stats

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README dynamically
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Nayemjaman
          template: classic
          base: header, repositories, activity, community, metadata
          config_timezone: Asia/Dhaka
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_followup: yes
          plugin_habits: yes
